/* ---------------- bundled snapshot (real articles, fresh pull 2026-07-19) ----------------
   Guarantees the feed is never empty. Live fetches replace these the moment they succeed.
   On a new build the cached articles from prior sessions are purged (see loadSnapshot). */
 const SNAPSHOT_TS = 1784489085000; // 2026-07-19 UTC (fresh pull)
 const SNAPSHOT = [
 {src:"tc-ai",d:"2026-07-19",t:"Can an Apple lawsuit derail OpenAI's hardware plans?",u:"https://techcrunch.com/2026/07/19/can-an-apple-lawsuit-derail-openais-hardware-plans/",s:"On the latest episode of Equity, we debate whether Apple's lawsuit will cast over OpenAi's much-discussed plans to get into hardware and go",img:null},
 {src:"tds",d:"2026-07-19",t:"Loop Engineering for RAG Question Parsing: The Small Loop That Runs Before Retrieval",u:"https://towardsdatascience.com/loop-engineering-for-rag-question-parsing-the-small-loop-that-runs-before-retrieval/",s:"Enterprise Document Intelligence [Vol.1 #6quinquies] - Prompt engineering, then context engineering, then loop engineering. On the question side, the",img:null},
 {src:"tc-ai",d:"2026-07-19",t:"Nonprofit Current AI is racing to build the World Wide Web of AI, free for all",u:"https://techcrunch.com/2026/07/19/nonprofit-current-ai-is-racing-to-build-the-world-wide-web-of-ai-free-for-all/",s:"Current AI, a non-profit building AI that leaves no one culture behind, has made remarkable progress across devices, AI chat and",img:null},
 {src:"tds",d:"2026-07-19",t:"Your AI Agent Passed Every Eval. Finance Still Killed It.",u:"https://towardsdatascience.com/your-ai-agent-passed-every-eval-finance-still-killed-it/",s:"An AI agent passed every metric in the eval harness I published, then the CFO killed it - its successful resolutions cost more than the humans it",img:null},
 {src:"decoder",d:"2026-07-19",t:"Alibaba's Qwen takes on Kimi K3 with open-weight Qwen 3.8, says model is 'second only to Fable 5'",u:"https://the-decoder.com/alibabas-qwen-takes-on-kimi-k3-with-open-weight-qwen-3-8-says-model-is-second-only-to-fable-5/",s:"Alibaba has unveiled Qwen 3.8, a multimodal AI model with 2.4 trillion parameters that the Qwen team says rivals leading models and trails only Fable",img:"https://the-decoder.com/wp-content/uploads/2026/07/qwen_logo-1.png"},
 {src:"decoder",d:"2026-07-19",t:"Google Deepmind argues video generators already contain the world models computer vision has been missing",u:"https://the-decoder.com/google-deepmind-argues-video-generators-already-contain-the-world-models-computer-vision-has-been-missing/",s:"Google Deepmind's GenCeption repurposes a video generator for classic vision tasks such as depth estimation and segmentation, matching",img:"https://the-decoder.com/wp-content/uploads/2026/07/google-deepmind-genception-generated-image-nano-banana-pro.jpg"},
 {src:"kdn",d:"2026-07-19",t:"Could Your AI Systems Already Be High-Risk Under the EU AI Act?",u:"https://www.kdnuggets.com/2026/07/airia/could-your-ai-systems-already-be-high-risk-under-the-eu-ai-act",s:"Access the on-demand webinar to understand what the latest guidance means for your AI governance program and what your organization should do",img:null},
 {src:"decoder",d:"2026-07-19",t:"Moonshot's Kimi K3 outperforms Fable 5 in frontend code but lags far behind in complex math",u:"https://the-decoder.com/moonshots-kimi-k3-outperforms-fable-5-in-frontend-code-but-lags-far-behind-in-complex-math/",s:"Moonshot's Kimi K3 is the first Chinese model to top the Code Arena: Frontend rankings, beating Claude Fable 5 and GPT-5.6 Sol by a wide margin. But",img:"https://the-decoder.com/wp-content/uploads/2026/06/kimi_logo.png"},
 {src:"fff",d:"2026-07-19",t:"Blueberry Cottage Cheese Biscuits with Streusel Topping",u:"https://fitfoodiefinds.com/blueberry-cottage-cheese-biscuits/",s:"Blueberry Cottage Cheese Biscuits with Streusel Topping Remember my cottage cheese breakfast biscuits? These blueberry biscuits are their sweet,",img:"https://fitfoodiefinds.com/wp-content/uploads/2026/07/Blueberry-Crumble-Protein-Buns-2-1200x1800.jpg"},
 {src:"hn",d:"2026-07-19",t:"OpenAI reduces Codex Model Context Size from 372k to 272k",u:"https://github.com/openai/codex/pull/33972/files",s:"Article URL: https://github.com/openai/codex/pull/33972/files Comments URL: https://news.ycombinator.com/item?id=48965850 Points: 272 # Comments:",img:null},
 {src:"simonw",d:"2026-07-19",t:"Claude Code uses Bun written in Rust now",u:"https://simonwillison.net/2026/Jul/19/claude-code-in-bun-in-rust/",s:"In Rewriting Bun in Rust Jarred Sumner made the following claim: Claude Code v2.1.181 (released June 17th) and later use the Rust port of Bun.",img:null},
 {src:"tc-ai",d:"2026-07-18",t:"Kimi: Threat or menace?",u:"https://techcrunch.com/2026/07/18/kimi-threat-or-menace/",s:"Chinese company Moonshot AI released a new version of its Kimi model this week, prompting concern about 'full AI",img:null},
 {src:"tds",d:"2026-07-18",t:"Many Companies Use AI. Few Know How to Build an AI-Native Enterprise Data Platform.",u:"https://towardsdatascience.com/many-companies-use-ai-few-know-how-to-build-an-ai-native-enterprise-data-platform/",s:"A practical enterprise AI architecture with data agents, AI-powered QA, and AI governance. The post Many Companies Use AI. Few Know How to Build an",img:null},
 {src:"sd-nut",d:"2026-07-18",t:"Popular sugar substitutes linked to faster brain aging",u:"https://www.sciencedaily.com/releases/2026/07/260717033213.htm",s:"Several popular sugar substitutes may not be as harmless as they seem. Adults who consumed the most artificial sweeteners showed substantially faster",img:null},
 {src:"kdn",d:"2026-07-18",t:"KDnuggets Weekly Roundup: Week of July 13, 2026",u:"https://www.kdnuggets.com/kdnuggets-weekly-roundup-2026-07-13",s:"Stop Using If-Else Chains: Use the Registry Pattern in Python Instead - 5 Real-World SQL Projects to Build Your Data Portfolio - 10 YouTube Channels",img:null},
 {src:"simonw",d:"2026-07-18",t:"Claude make Fable 5 permanent",u:"https://simonwillison.net/2026/Jul/18/claude-make-fable-5-permanent/",s:"Claude make Fable 5 permanent An update from the @claudeai account on Twitter: Beginning July 20, Claude Fable 5 will be included in all Max and Team",img:null},
 {src:"latent",d:"2026-07-18",t:"[AINews] not much happened today",u:"https://www.latent.space/p/ainews-not-much-happened-today-830",s:"a quiet",img:"https://substackcdn.com/image/youtube/w_728,c_limit/OqM67QG_Ikk"},
 {src:"sd-nut",d:"2026-07-18",t:"Mediterranean diet may activate tiny proteins that protect the heart and brain",u:"https://www.sciencedaily.com/releases/2026/07/260716023605.htm",s:"The Mediterranean diet may influence aging through tiny proteins produced inside the cell's mitochondria. Older adults who followed the diet most",img:null},
 {src:"mommyp",d:"2026-07-18",t:"Cottage Cheese Ice Cream Recipe (High Protein)",u:"https://mommypotamus.com/mango-cottage-cheese-ice-cream-recipe/",s:"... Read more Continue reading Cottage Cheese Ice Cream Recipe (High",img:null},
 {src:"chalk",d:"2026-07-17",t:"We Tried the Longevity Supplement Backed by 18 Years of Research and 25 Clinical Trials",u:"https://thechalkboardmag.com/timeline-mitopure-review/",s:"we're constantly testing supplements, speaking with experts, and keeping tabs on the newest ingredients promising to support how we age. From",img:"https://thechalkboardmag.com/wp-content/uploads/2026/05/tcm-timeline-01-300x242.webp"},
 {src:"skinny",d:"2026-07-17",t:"Free 7 Day Healthy Meal Plan (July 20-26)",u:"https://www.skinnytaste.com/free-7-day-healthy-meal-plan-july-20-26/",s:"A free 7-day, flexible weight loss meal plan including breakfast, lunch and dinner ideas and a shopping list. All recipes include macros and Weight",img:null},
 {src:"hf",d:"2026-07-17",t:"Fine-tune video and image models at scale with NVIDIA NeMo Automodel and Diffusers",u:"https://huggingface.co/blog/nvidia/scale-diffusers-finetuning-nemo-automodel",s:"",img:null},
 {src:"simonw",d:"2026-07-17",t:"Quoting Kimi K3",u:"https://simonwillison.net/2026/Jul/17/kimi-k3/",s:"Is there something I can actually help you with today? Kimi K3 , after refusing to leak its system prompt Tags: kimi , ai-personality , generative-ai",img:null},
 {src:"mittr",d:"2026-07-17",t:"The Download: perimenopause misinformation and China's latest AI leap",u:"https://www.technologyreview.com/2026/07/17/1140640/the-download-perimenopause-misinformation-china-moonshot-ai/",s:"This is today's edition of The Download, our weekday newsletter that provides a daily dose of what's going on in the world of technology. There's a",img:"https://wp.technologyreview.com/wp-content/uploads/2024/12/Varcor-Facility-Interiorpoop-thumb.jpg"},
 {src:"kdn",d:"2026-07-17",t:"5 FREE Resources on Agentic AI",u:"https://www.kdnuggets.com/5-free-resources-on-agentic-ai",s:"Here are 5 curated resources to help you progress your agentic AI learning for",img:null},
 {src:"wm",d:"2026-07-17",t:"5 Simple & Natural Detox Bath Recipes",u:"https://wellnessmama.com/beauty/detox-bath-recipes/",s:"Nothing is more relaxing than a warm bath... except a relaxing detox bath. These are a great option for anyone who struggles with skin issues or",img:null},
 {src:"chalk",d:"2026-07-17",t:"Train Like Jennifer Aniston This Summer: We Asked Her Trainer For The Workout Routine",u:"https://thechalkboardmag.com/train-like-jennifer-aniston-workout-routine/",s:"Some of the links in this story are affiliate links, which means we may earn a commission if you choose to purchase, helping us continue to share",img:"https://thechalkboardmag.com/wp-content/uploads/2026/07/image2-5-300x208.webp"},
 {src:"zapier",d:"2026-07-17",t:"OpenClaw vs. Zapier: What's the difference? [2026]",u:"https://zapier.com/blog/openclaw-vs-zapier",s:"If you've spent any time in AI automation circles this year, you've probably heard about OpenClaw. The open-source AI agent went from a side project",img:null},
 {src:"zapier",d:"2026-07-17",t:"16 AI prompt templates for better AI agent outputs",u:"https://zapier.com/blog/ai-prompt-templates",s:"I've gone through a lot of painful trial and error with AI prompting-a lot. Which was fine when I was experimenting in back-and-forth conversations",img:null},
 {src:"zapier",d:"2026-07-17",t:"Agentic AI vs. RPA: Everything you need to know",u:"https://zapier.com/blog/agentic-ai-vs-rpa",s:"Automation has evolved far beyond simple scripts and basic workflows. While robotic process automation (RPA) has long been used to handle repetitive,",img:null},
 {src:"latent",d:"2026-07-17",t:"[AINews] Kimi K3 2.8T-A50B: the largest open model ever released; Opus 4.8-class at Sonnet 5 pricing",u:"https://www.latent.space/p/ainews-kimi-k3-28t-a50b-the-largest",s:"a great week for open models",img:"https://substackcdn.com/image/fetch/$s_!xVk0!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7d22c3fe-fde7-4c91-9e50-83b1597fe747_1958x1160.png"},
 {src:"vb-ai",d:"2026-07-16",t:"The AI compute gap: Enterprises are buying infrastructure faster than they can measure what it costs",u:"https://venturebeat.com/ai/the-ai-compute-gap-enterprises-are-buying-infrastructure-faster-than-they-can-measure-what-it-costs",s:"Across 107 enterprises, AI infrastructure spending is accelerating well ahead of the ability to see or steer its economics. Most organizations run",img:"https://images.ctfassets.net/jdtwqhzvc2n1/65A33lcUi9p0nBSloUI1Wo/5e5d26295bc879f0ea8845cecac65504/VentureBeat-Research.png"},
 {src:"vb-ai",d:"2026-07-16",t:"The agent security gap: 54% of enterprises have already had an AI agent incident, and most still let agents share credentials",u:"https://venturebeat.com/ai/the-agent-security-gap-54-of-enterprises-have-already-had-an-ai-agent-incident-and-most-still-let-agents-share-credentials",s:"Across 107 enterprises, AI agents are being given real access to systems and data while the controls meant to contain them lag behind. More than half",img:"https://images.ctfassets.net/jdtwqhzvc2n1/3YcL8Sbx04RQsgnRvbYfs5/0567154029abc3d37ccfad9b6cc5f370/VentureBeat-Research-1.png"},
 {src:"vb-ai",d:"2026-07-16",t:"The AI context gap: Enterprise AI organizations have a trust problem, not a retrieval problem - and most are still building the fix",u:"https://venturebeat.com/ai/the-ai-context-gap-enterprise-ai-organizations-have-a-trust-problem-not-a-retrieval-problem-and-most-are-still-building-the-fix",s:"Across 101 enterprises, the infrastructure that feeds AI agents their business context is being built faster than it can be trusted.",img:"https://images.ctfassets.net/jdtwqhzvc2n1/65A33lcUi9p0nBSloUI1Wo/5e5d26295bc879f0ea8845cecac65504/VentureBeat-Research.png"},
 {src:"fff",d:"2026-07-16",t:"10 No-Cook Dinners (for when it's too hot to function!)",u:"https://fitfoodiefinds.com/10-no-cook-dinners/",s:"10 No-Cook Dinners (for when it's too hot to function!) It's 95 and the last thing I want to do is turn on my oven. Same? These are 10 dinners...",img:"https://fitfoodiefinds.com/wp-content/uploads/2024/02/Spring-Roll-Salad-8-1200x1200.jpg"},
 {src:"fatherly",d:"2026-07-16",t:"Get Into a Back-to-School Mindset With Advice From 12 Youth Soccer Coaches",u:"https://www.fatherly.com/parenting/school-advice-from-youth-league-soccer-coaches",s:"Here's how youth sports coaches can get you in the right mindset for",img:"https://imgix.bustle.com/uploads/getty/2026/7/9/fed0073c/a-father-son-wearing.jpg"},
 {src:"googai",d:"2026-07-16",t:"Create, edit and star in videos with two Google Vids updates",u:"https://blog.google/products-and-platforms/products/workspace/gemini-omni-personal-avatars/",s:"Gemini Omni and personal avatars in Google Vids make video creation easier than",img:"https://storage.googleapis.com/gweb-uniblog-publish-prod/images/omni-blog-header_OarEe2t.max-600x600.format-webp.webp"},
 {src:"mittr",d:"2026-07-16",t:"The Download: OpenAI unveils GPT-Red and heat pumps rise in the US",u:"https://www.technologyreview.com/2026/07/16/1140600/the-download-openai-unveils-gpt-red-heat-pumps-rise-us/",s:"This is today's edition of The Download, our weekday newsletter that provides a daily dose of what's going on in the world of technology. Meet",img:"https://wp.technologyreview.com/wp-content/uploads/2024/12/bed.jpg"},
 {src:"nf",d:"2026-07-16",t:"Do Cranberries and Pumpkin Seeds Help an Enlarged Prostate?",u:"https://nutritionfacts.org/blog/do-cranberries-and-pumpkin-seeds-help-an-enlarged-prostate/",s:"Cranberries and pumpkin seeds are put to the test for benign prostatic hypertrophy. More than 50% of men in their 50s and at least 70%",img:"https://assets.nutritionfacts.org/2026/06/2-05.png"},
 {src:"hf",d:"2026-07-16",t:"Newer Models, Same Advantage",u:"https://huggingface.co/blog/Dharma-AI/newer-models-same-advantages",s:"",img:null},
 {src:"deepmind",d:"2026-07-16",t:"Our approach to bioresilience",u:"https://deepmind.google/blog/our-approach-to-bioresilience/",s:"Google DeepMind and Isomorphic Labs are sharing our joint approach to bioresilience and AI",img:null},
 {src:"latent",d:"2026-07-16",t:"[AINews] Thinky's Inkling: 975B-A41B multimodal, new best American Apache 2.0 open model (with Inkling-Small, 276B-A12B)",u:"https://www.latent.space/p/ainews-thinkys-inkling-975b-a41b",s:"Thinky's first full LLM release is a banger and bonus: it's open",img:"https://substackcdn.com/image/fetch/$s_!AvrX!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F90048da3-a87f-44d8-8ad4-e954031d2721_2540x1692.png"},
 {src:"openai",d:"2026-07-16",t:"How Cars24 scales conversations and builds faster with OpenAI",u:"https://openai.com/index/cars24",s:"Cars24 uses OpenAI-powered voice and chat agents to handle 1M+ monthly conversation minutes, recover 12% of lost leads, and bring agentic workflows",img:null},
 {src:"hf",d:"2026-07-16",t:"Security incident disclosure - July 2026",u:"https://huggingface.co/blog/security-incident-july-2026",s:"",img:null},
 {src:"chalk",d:"2026-07-15",t:"Why Andrew Huberman And Sleep Experts Keep Talking About Morning Light",u:"https://thechalkboardmag.com/andrew-huberman-morning-light/",s:"Morning light has become one of those wellness recommendations you hear everywhere once you start noticing it. Sleep doctors bring it up. Functional",img:"https://thechalkboardmag.com/wp-content/uploads/2026/07/tcm-morning-light-03-300x208.webp"},
 {src:"skinny",d:"2026-07-15",t:"Smashed Salmon Broccoli Rice Bowls",u:"https://www.skinnytaste.com/salmon-broccoli-rice-bowls/",s:"Spicy Smashed Salmon Broccoli Rice Bowl is a quick, 30-minute, protein-packed dinner made with roasted salmon, broccoli, rice, and a creamy spicy",img:null},
 {src:"fff",d:"2026-07-15",t:"Strawberry Smoothie (4 Ingredients, No Ice!)",u:"https://fitfoodiefinds.com/strawberry-smoothie/",s:"Strawberry Smoothie (4 Ingredients, No Ice!) After testing this strawberry smoothie with every liquid in my fridge - almond milk, regular milk, even",img:"https://fitfoodiefinds.com/wp-content/uploads/2019/03/STRAWBERRY-sq.png"},
 {src:"mittr",d:"2026-07-15",t:"Meet GPT-Red: an LLM super-hacker OpenAI built to make its models safer",u:"https://www.technologyreview.com/2026/07/15/1140514/meet-gpt-red-an-llm-super-hacker-openai-built-to-make-its-models-safer/",s:"OpenAI has built an LLM super-hacker called GPT-Red that it uses as a sparring partner to help its other models boost their defenses against",img:null},
 {src:"noot",d:"2026-07-15",t:"Ashwagandha",u:"https://nootropicsexpert.com/ashwagandha/",s:"Ashwagandha has been shown to repair and reverse damage to the brain caused by chronic anxiety and stress. In a hurry - click here to learn more",img:null},
 {src:"fatherly",d:"2026-07-15",t:"35 Back-To-School Sports Gear Essentials Every Young Athlete Needs",u:"https://www.fatherly.com/gear/essential-sports-gear-for-youthg-sports",s:"From activewear to snacks to the crucial stuff we all forget about, here's your complete product guide to the gear your young athlete",img:"https://imgix.bustle.com/uploads/image/2026/7/10/5e294737/35sportsessentials_header.jpg"},
 {src:"openai",d:"2026-07-15",t:"GPT-Red: Unlocking Self-Improvement for Robustness",u:"https://openai.com/index/unlocking-self-improvement-gpt-red",s:"Explore GPT-Red, OpenAI's automated red teaming system that uses self-play to improve AI safety, alignment, and prompt injection",img:null},
 {src:"noot",d:"2026-07-14",t:"Lion's Mane",u:"https://nootropicsexpert.com/lions-mane/",s:"Lion's Mane Mushroom is known for stimulating Nerve Growth Factor, improving cognition and memory, and relieving depression. In a hurry - click here",img:null},
 {src:"fff",d:"2026-07-14",t:"Peanut Butter Protein Balls (No Food Processor!)",u:"https://fitfoodiefinds.com/peanut-butter-protein-balls-recipe/",s:"Peanut Butter Protein Balls (No Food Processor!) I've been making peanut butter protein balls since before Fit Foodie Finds even launched in 2010 -",img:"https://fitfoodiefinds.com/wp-content/uploads/2020/04/protein-balls-sq.jpg"},
 {src:"noot",d:"2026-07-14",t:"Passionflower",u:"https://nootropicsexpert.com/passionflower/",s:"Passionflower is known for improving sleep quality, reducing anxiety, and promoting healthy brain GABA levels. Passionflower (Passiflora incarnata,",img:null},
 {src:"sd-nut",d:"2026-07-14",t:"Eating chili peppers may raise the risk of one deadly cancer",u:"https://www.sciencedaily.com/releases/2026/07/260713084921.htm",s:"A major review found that people who consumed the most chili peppers had a substantially higher risk of esophageal cancer, though the evidence was",img:null},
 {src:"nf",d:"2026-07-14",t:"The Science Behind Oatmeal and Diabetes",u:"https://nutritionfacts.org/blog/the-science-behind-oatmeal-and-diabetes/",s:"Before Insulin, There Was Oatmeal Before the discovery of insulin, the lives of many people with diabetes were saved or prolonged by Carl von",img:"https://assets.nutritionfacts.org/2026/07/screenshot-2026-06-30-at-083817.png"},
 {src:"openai",d:"2026-07-14",t:"How to manage AI investments in the agentic era",u:"https://openai.com/index/managing-ai-investments-in-agentic-era",s:"Learn how enterprises can manage AI investments in the agentic era by measuring useful work per dollar, improving efficiency, and scaling high-value",img:null},
 {src:"noot",d:"2026-07-13",t:"Caffeine",u:"https://nootropicsexpert.com/caffeine/",s:"Caffeine enhances alertness, stabilizes mood, boosts memory and cognition, and improves athletic performance In a hurry - click here to learn more",img:null},
 {src:"skinny",d:"2026-07-13",t:"High-Protein Ratatouille Lasagna Has 39g Protein and No Noodles",u:"https://www.skinnytaste.com/ratatouille-lasagna/",s:"This Noodle-less Ratatouille Lasagna is a high-protein, gluten-free vegetarian dinner made with summer vegetables and cottage cheese, with over 39g",img:null},
 {src:"deepmind",d:"2026-07-13",t:"Empowering India's next generation of innovators with ATL Saathi",u:"https://deepmind.google/blog/empowering-indias-next-generation-of-innovators-with-atl-saathi/",s:"Google and AIM launched ATL Saathi, a Gemini-powered AI tool empowering Indian educators in robotics",img:null},
 {src:"skinny",d:"2026-07-12",t:"Feta-Brined Chicken Bowls with Salad Shirazi",u:"https://www.skinnytaste.com/feta-brined-chicken-bowls/",s:"These Feta Brined Grilled Chicken Bowls feature juicy, flavorful chicken breasts marinated in feta brine and served over rice with fresh Shirazi",img:null},
 {src:"sd-fit",d:"2026-07-12",t:"Columbia scientists discover surprising link between serotonin and heart valve disease",u:"https://www.sciencedaily.com/releases/2026/07/260711010131.htm",s:"Scientists have uncovered evidence that serotonin, the chemical best known for regulating mood, may also speed the progression of a common heart",img:null},
 {src:"sd-nut",d:"2026-07-10",t:"Scientists found a longevity diet that helped mice eat more and lose fat",u:"https://www.sciencedaily.com/releases/2026/07/260708022206.htm",s:"Scientists found that a modified Mediterranean-style diet with low protein and just enough methionine helped mice live healthier lives while reducing",img:null},
 {src:"wm",d:"2026-07-09",t:"DIY Natural Tinted Lip Sunscreen",u:"https://wellnessmama.com/beauty/lip-sunscreen/",s:"For many years now I've preached about the benefits of safe sun exposure. The keyword here is safe! And while it has a lot of benefits, sometimes on",img:null},
 {src:"nf",d:"2026-07-09",t:"A Surprising Vegetable Approach to Insomnia",u:"https://nutritionfacts.org/blog/a-surprising-vegetable-approach-to-insomnia/",s:"Lactucin, the hypnotic component of lettuce, is put to the test in a randomized, double-blind, placebo-controlled trial of lettuce seeds. 'There is a",img:"https://assets.nutritionfacts.org/2026/07/2-04.png"},
 {src:"rll",d:"2026-07-08",t:"Navigating Parent Burnout While Homeschooling Neurodivergent Kids",u:"https://raisinglifelonglearners.com/navigating-parent-burnout-while-homeschooling-neurodivergent-kids/",s:"Homeschooling takes everything you have. Homeschooling a neurodivergent child takes everything-and more-you didn't know you could give. So often the",img:null},
 {src:"wm",d:"2026-07-07",t:"Broccoli Cheddar Egg Bake (Easy High-Protein)",u:"https://wellnessmama.com/recipes/egg-bake/",s:"I love having simple breakfast recipes I can make ahead for busy mornings. While smoothies and overnight oats have their place, I also try to",img:null},
 {src:"googai",d:"2026-07-07",t:"Expanding Managed Agents in Gemini API: background tasks, remote MCP and more",u:"https://blog.google/innovation-and-ai/technology/developers-tools/expanding-managed-agents-gemini-api/",s:"We're announcing new capabilities in Managed Agents in Gemini API so developers can build reliable, production-ready",img:"https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Managed_agents_feature_bundle_l.max-600x600.format-webp.webp"},
 {src:"kresser",d:"2026-07-07",t:"RHR: Your Mouth is Talking To Your Brain-And You Should Be Listening",u:"https://chriskresser.com/your-mouth-is-talking-to-your-brain-and-you-should-be-listening/",s:"What if one of the most overlooked risk factors for cognitive decline isn't in the brain-but in the mouth? In this episode of Revolution Health",img:null},
 {src:"sd-fit",d:"2026-07-05",t:"Scientists discover the deep sleep circuit that builds muscle, burns fat, and boosts the brain",u:"https://www.sciencedaily.com/releases/2026/06/260626030433.htm",s:"Researchers have identified the brain circuitry that links deep sleep with the release of growth hormone, revealing how the two regulate each other.",img:null},
 {src:"deepmind",d:"2026-07-03",t:"Google DeepMind and A24 announce first-of-its-kind research partnership",u:"https://deepmind.google/blog/google-deepmind-and-a24-announce-first-of-its-kind-research-partnership/",s:"",img:null},
 {src:"sd-fit",d:"2026-07-03",t:"Old muscle stem cells can act young again but there's a catch",u:"https://www.sciencedaily.com/releases/2026/06/260622014315.htm",s:"Scientists at UCLA discovered a surprising reason aging muscles heal more slowly. In older muscle stem cells, a protein called NDRG1 builds up and",img:null},
 {src:"nf",d:"2026-07-02",t:"Can Exercise Counteract a High-Fat Meal?",u:"https://nutritionfacts.org/blog/can-exercise-counteract-a-high-fat-meal/",s:"There is a window of time in which sufficient physical activity can help mediate some of the damage caused by eating an unhealthy meal. I've",img:"https://assets.nutritionfacts.org/2026/07/0-47.png"},
 {src:"mommyp",d:"2026-06-30",t:"The Complete Dorm Room Essentials List (Wellness Edition)",u:"https://mommypotamus.com/dorm-room-essentials-checklist/",s:"... Read more Continue reading The Complete Dorm Room Essentials List (Wellness",img:null},
 {src:"wm",d:"2026-06-30",t:"Homemade Greek Seasoning",u:"https://wellnessmama.com/recipes/greek-seasoning/",s:"One of the best ways to make healthy eating easy is to keep some homemade staples on hand. Simple DIY spice blends and sauces take very little effort",img:null},
 {src:"rll",d:"2026-06-28",t:"Great Books to Read With Your Kids in July",u:"https://raisinglifelonglearners.com/great-books-to-read-with-your-kids-in-july/",s:"We are in the middle of summer, folks! Let's work together to keep our kids' bodies moving and their minds busy with this list of great books to read",img:null},
 {src:"sigmund",d:"2026-06-27",t:"My Child Has Anxiety: Why avoidance makes it worse, and what to do intead.",u:"https://heysigmund.com/my-child-has-anxiety-why-avoidance-makes-it-worse-and-what-to-do-intead/",s:"You know the feeling. Tears at drop off. The tummy aches that crash into your world on a Sunday night. The party, the play date that's meant to be",img:null},
 {src:"rll",d:"2026-06-26",t:"Navigating Sibling Conflict and Neurodivergence in Your Homeschool",u:"https://raisinglifelonglearners.com/navigating-sibling-conflict-and-neurodivergence-in-your-homeschool/",s:"It's the universal family refrain: 'That's not fair!' If you have more than one child, you've heard it-sometimes on a daily basis. In neurodivergent",img:null},
 {src:"rll",d:"2026-06-18",t:"Real-Life Homeschool Rhythms for Neurodivergent Kids",u:"https://raisinglifelonglearners.com/real-life-homeschool-rhythms-for-neurodivergent-kids/",s:"'How am I supposed to teach all these kids at once?' If there's ever been a thought that repeats itself on a loop during your homeschool days, it",img:null},
 {src:"sd-fit",d:"2026-06-17",t:"10 surprising ways diabetes and dementia are connected",u:"https://www.sciencedaily.com/releases/2026/06/260616103128.htm",s:"Diabetes and dementia appear to be closely intertwined, with each condition potentially influencing the other. Problems with insulin and glucose can",img:null},
 {src:"rll",d:"2026-06-15",t:"Interest-Led Homeschooling and Your Gifted Child",u:"https://raisinglifelonglearners.com/the-gifted-child-and-delight-directed-homeschooling-2/",s:"I love sharing stories of other parents parenting and homeschooling gifted kids. This is Heather's... Billy is gifted. He is 5 and knows how to add,",img:null},
 {src:"mollick",d:"2026-06-09",t:"What it feels like to work with Mythos",u:"https://www.oneusefulthing.org/p/what-it-feels-like-to-work-with-mythos",s:"Claude Fable represents another big jump in",img:"https://substackcdn.com/image/fetch/$s_!hxhY!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ff58114c7-7286-4a9f-ab75-3c8a7e414dc3_2382x1247.png"},
 {src:"simpleh",d:"2026-06-09",t:"4 Fun Ways to Enjoy Summer Homeschooling",u:"https://simplehomeschool.net/summer-homeschooling/",s:"4 Fun Ways to Enjoy Summer Homeschooling ~ Written by Cait Curley Our family just wrapped up a 3-day soccer tournament and the kids are prepping for",img:"https://simplehomeschool.net/wp-content/uploads/2021/06/boys-3396713_640.jpg"},
 {src:"simpleh",d:"2026-05-27",t:"How to homeschool a kid who hates to write",u:"https://simplehomeschool.net/hates-to-write/",s:"How to Homeschool a Kid Who Hates to Write ~ Written by Anne Bogel of Modern Mrs. Darcy For whatever reason, some kids hate to write. I don't mean",img:"https://simplehomeschl.wpengine.com/wp-content/uploads/2014/04/simple-homeschool-writingpicmo.jpg"},
 {src:"fatherly",d:"2026-05-04",t:"'Do I Have To Go To College?'",u:"https://www.fatherly.com/parenting/go-the-fck-to-college-essay-adam-mansbach",s:"The author of 'Go The F*ck to Sleep' and now 'Go The F*ck to College' explores the real joy and pain of sending your kid off to school once and for",img:"https://imgix.bustle.com/uploads/image/2026/4/27/4269fdf5/untitled-design.jpg"},
 {src:"simpleh",d:"2026-04-13",t:"Homeschooling with Trauma: My Story",u:"https://simplehomeschool.net/homeschooling-with-trauma/",s:"Homeschooling with Trauma: My Story ~ Written by Jamie C. Martin of Simple Homeschool Five years ago my inner world began to collapse, and it felt",img:"https://simplehomeschool.net/wp-content/uploads/2026/04/sunset-1024x574.jpeg"},
 {src:"fatherly",d:"2026-04-13",t:"Gary Vaynerchuk Just Wants Us All To Be (And Raise) Nice Guys",u:"https://www.fatherly.com/life/gary-vaynerchuk-interview-manosphere-boys",s:"In conversation with Gary Vaynerchuk about raising boys, the manosphere, the key to making money, and",img:"https://imgix.bustle.com/uploads/getty/2026/4/13/cb871216/gary-vaynerchuk-chief-executive.jpg"},
 {src:"simpleh",d:"2026-03-27",t:"5 (Surprising) Things You Should Know About Homeschooling High School",u:"https://simplehomeschool.net/homeschooling-high-school/",s:"5 (surprising) things you need to know about homeschooling high school ~ Written by Shawna Wingert of Different by Design Learning For seven years",img:"https://simplehomeschool.net/wp-content/uploads/2021/03/Copy-of-Copy-of-When-Your-Child-Isnt-At-Grade-Level-15.png"},
 {src:"simpleh",d:"2026-03-20",t:"The 5 love languages of homeschooling",u:"https://simplehomeschool.net/love-languages/",s:"The 5 love languages of homeschooling ~Written by Jamie C. Martin of Simple Homeschool A few weeks ago an issue with one of my children kept me up",img:"https://simplehomeschool.net/wp-content/uploads/2014/10/The-5-love-languages-of-homeschooling.jpg"},
 {src:"lansbury",d:"2026-03-16",t:"Why Parents Need RIE (with Melani Ladygo)",u:"https://www.janetlansbury.com/2026/03/why-parents-need-rie-with-melani-ladygo/",s:"You may have heard Janet, other parents, or early childhood professionals speak about 'RIE' (pronounced 'rye'). Perhaps they described 'RIE' as",img:null},
 {src:"simpleh",d:"2026-02-19",t:"THE best vs. YOUR best",u:"https://simplehomeschool.net/the-best-vs-your-best/",s:"The Best vs. YOUR Best ~ Written by Jamie C. Martin of Simple Homeschool Instead of focusing on giving our children a complete education, or a",img:"https://simplehomeschl.wpengine.com/wp-content/uploads/2016/01/THE-best-vs.-YOUR-best.jpg"},
 {src:"sigmund",d:"2026-01-19",t:"The Power of 'and ' to Build Their Brave",u:"https://heysigmund.com/the-power-of-and-to-build-their-brave/",s:"Children will read our anxiety as our belief that they are unsafe, incapable, and not ready for brave. A way to move through this is to remember the",img:null},
 {src:"fatherly",d:"2025-12-01",t:"Are Our Chidlren Really So Mentally Unwell?",u:"https://www.fatherly.com/parenting/children-mental-health-industrial-complex-autism-adhd",s:"American kids are having a mental health crisis like no other. What are we to do with all these",img:"https://imgix.bustle.com/uploads/getty/2025/12/1/708667c6/a-row-of-students.jpg"},
 {src:"lansbury",d:"2025-10-05",t:"Making a Successful Transition to Preschool (with Mr. Chazz)",u:"https://www.janetlansbury.com/2025/10/making-a-successful-transition-to-preschool-with-mr-chazz/",s:"Janet welcomes a timely visit from iconic educator Mr. Chazz who shares how parents and teachers can help kids successfully transition to a new",img:null},
 {src:"lansbury",d:"2025-10-05",t:"The Bad Advice I Gave About Toilet Training",u:"https://www.janetlansbury.com/2025/10/the-bad-advice-i-gave-about-toilet-training/",s:"In a previous 'Unruffled' episode, Janet offered advice to a parent who was struggling with potty training. That parent wrote back recently to",img:null},
 {src:"sigmund",d:"2025-09-05",t:"The Key to Crime Prevention and Mental Illness Prevention - Why it Lies in Our Schools and Early Childhood Centres",u:"https://heysigmund.com/schools-early-childhood-centres/",s:"Educators are exhausted. Why wouldn't they be? They are carrying a lot - learning outcomes, curriculum demands, behavioural challenges, family needs,",img:null},
 {src:"sigmund",d:"2025-09-04",t:"Let's talk about 'The Brave Space'",u:"https://heysigmund.com/brave-space/",s:"Brave rarely feels brave. Mostly, it feels like anxious, scared, stressed, nervous, hard, clumsy, or awkward. This is the brave space - the space",img:null},
 {src:"lansbury",d:"2025-08-10",t:"Healthy Body Image, Eating Disorders: What Parents Need to Know (with Grace Lautman, CN, LMHC)",u:"https://www.janetlansbury.com/2025/08/healthy-body-image-eating-disorders-what-parents-need-to-know-with-grace-lautman-cn-lmhc/",s:"Janet is joined by Grace Lautman, a therapist and nutritionist who focuses on eating disorders, the conditions that can create and aggravate them,",img:null},
 {src:"lansbury",d:"2025-08-10",t:"Rejection, Exclusion, Teasing-What to do When Friends Aren't Kind",u:"https://www.janetlansbury.com/2025/08/rejection-exclusion-teasing-what-to-do-when-friends-arent-kind/",s:"We all want our kids to enjoy thriving friendships, to feel appreciated by supportive peers. But that's not always case, and it can be heartbreaking",img:null},
 {src:"fatherly",d:"2025-08-01",t:"The Best Back-to-School Books For Every Age and Stage",u:"https://www.fatherly.com/entertainment/best-back-to-school-books-2025",s:"With kids heading back to school in 2025, here's some great books to both get them ready, but also, to remind kids why reading is",img:"https://imgix.bustle.com/uploads/getty/2025/8/1/708482b0/getty-2223344451.jpg"},
];

function loadSnapshot(){
  // Fresh-build cache purge: when a new snapshot ships, clear any stale articles
  // cached from earlier sessions so the feed reflects the latest pull (favorites &
  // collections are kept - they live in S.favs / S.library, not S.cache).
  if(S.snapTs !== SNAPSHOT_TS){
    articles.clear();
    S.cache = [];
    S.snapTs = SNAPSHOT_TS;
    saveState();
  }
  const items = SNAPSHOT.map((r,i)=>{
    const src = SOURCES.find(s=>s.id===r.src); if(!src || !r.u || !r.t) return null;
    const ts = r.d ? (Date.parse(r.d) || SNAPSHOT_TS) : SNAPSHOT_TS;
    return {
      id: hash(normalizeLink(r.u)), link: r.u, title: r.t, ts,
      src: src.id, cat: src.cat, img: r.img||null, snippet: r.s||'', author:'',
      content:'', snap:true, brief:null,
    };
  }).filter(Boolean);
  mergeArticles(items);
  return items.length;
}
