/* ---------------- bundled snapshot (real articles, fetched at build time) ----------------
   Guarantees the feed is never empty — even in viewers that block network access.
   Live fetches replace these entries the moment they succeed. */
const SNAPSHOT_TS = 1784235174695; // 2026-07-16 UTC
const SNAPSHOT = [
 // TechCrunch AI
 {src:"tc-ai",d:"2026-07-13",t:"Already rich, already successful, why the last wave of tech winners is grinding again",u:"https://techcrunch.com/2026/07/13/already-rich-already-successful-why-the-last-wave-of-tech-winners-is-grinding-again/",s:"Analysis of how previous tech winners face renewed competitive pressures and challenges.",img:"https://techcrunch.com/wp-content/uploads/2024/04/53679979052_da1066fe91_o.jpg?w=668"},
 {src:"tc-ai",d:"2026-07-13",t:"Video-generation startup PixVerse raises $439M, valuation soars past $2B",u:"https://techcrunch.com/2026/07/13/video-generation-startup-pixverse-raises-439m-valuation-soars-past-2b/",s:"AI video creation platform PixVerse achieves unicorn status following significant funding round.",img:"https://techcrunch.com/wp-content/uploads/2026/07/69c14912d8f2b4b74d7b13ba_Copy-of-Red-Yellow-Retro-Vibrant-2025-Monthly-Calendar-1280-x-720-px-1200-x-630-px-8.jpeg?w=668"},
 {src:"tc-ai",d:"2026-07-13",t:"Hermes agent maker Nous Research in talks for new funding at $1.5B valuation",u:"https://techcrunch.com/2026/07/13/hermes-agent-maker-nous-research-in-talks-for-new-funding-at-1-5b-valuation/",s:"AI agent developer Nous Research pursues fresh investment at significant valuation increase.",img:"https://techcrunch.com/wp-content/uploads/2025/02/GjsjauvbsAAgUtD.jpeg?w=473"},
 {src:"tc-ai",d:"2026-07-13",t:"Satya Nadella has issued a shocking warning to companies using AI",u:"https://techcrunch.com/2026/07/13/satya-nadella-has-issued-a-shocking-warning-to-companies-using-ai/",s:"Microsoft CEO cautions organizations about potential risks and challenges in AI implementation.",img:"https://techcrunch.com/wp-content/uploads/2023/11/GettyImages-1778706504.jpg?w=575"},
 {src:"tc-ai",d:"2026-07-13",t:"The wildest allegations in Apple's trade secrets lawsuit against OpenAI",u:"https://techcrunch.com/2026/07/13/the-wildest-allegations-in-apples-trade-secrets-lawsuit-against-openai/",s:"Legal battle between Apple and OpenAI features extraordinary claims regarding intellectual property theft.",img:"https://techcrunch.com/wp-content/uploads/2026/07/tim-cook-sam-altman-GettyImages-2233062347.jpg?w=562"},
 {src:"tc-ai",d:"2026-07-13",t:"Sam Altman's space data center trash talk is what most experts already believe",u:"https://techcrunch.com/2026/07/13/sam-altmans-space-data-center-trash-talk-is-what-most-experts-already-believe/",s:"OpenAI chief's comments on orbital computing infrastructure align with prevailing industry sentiment.",img:"https://techcrunch.com/wp-content/uploads/2025/08/GettyImages-2223572243.jpg?w=563"},
 // The Decoder
 {src:"decoder",d:"2026-07-16",t:"Google rebrands NotebookLM as Gemini Notebook and opens its search app to third-party integration",u:"https://the-decoder.com/google-rebrands-notebooklm-as-gemini-notebook-and-opens-its-search-app-to-third-party-integration/",s:"Google renamed NotebookLM to Gemini Notebook with new code execution capabilities and integrated app connections.",img:null},
 {src:"decoder",d:"2026-07-16",t:"Germany puts Google's AI Overviews and Perplexity under media law in first-of-its-kind ruling",u:"https://the-decoder.com/germany-puts-googles-ai-overviews-and-perplexity-under-media-law-in-first-of-its-kind-ruling/",s:"German regulators classified AI overview tools as media subject to journalistic standards and liability.",img:"https://the-decoder.com/wp-content/uploads/2026/07/google_ai_overviews_germany.png"},
 {src:"decoder",d:"2026-07-16",t:"OpenAI wants developers to stop typing commands and start using a joystick to control their AI agents",u:"https://the-decoder.com/openai-wants-developers-to-stop-typing-commands-and-start-using-a-joystick-to-control-their-ai-agents/",s:"OpenAI and Work Louder launched the Codex Micro, a hardware controller for managing AI agents.",img:"https://the-decoder.com/wp-content/uploads/2026/07/openai-worklouder-codex-micro-02-overview-rgb.jpg"},
 {src:"decoder",d:"2026-07-16",t:"Sakana AI's orchestrator adds Nvidia Nemotron to prove \"collective intelligence\" can rival single frontier models",u:"https://the-decoder.com/sakana-ais-fugu-adds-nvidia-nemotron-to-prove-collective-intelligence-can-rival-single-frontier-models/",s:"Sakana AI integrated Nvidia's Nemotron into its orchestrator to demonstrate multi-model coordination.",img:"https://the-decoder.com/wp-content/uploads/2026/07/sakana-ai-nvidia-open-model-innovation.png"},
 {src:"decoder",d:"2026-07-16",t:"Ex-OpenAI CTO Murati's Thinking Machines drops Inkling, a 975B parameter model that leads US labs but trails China",u:"https://the-decoder.com/ex-openai-cto-muratis-thinking-machines-drops-inkling-a-975b-parameter-model-that-leads-us-labs-but-trails-china/",s:"Thinking Machines released Inkling, a 975-billion parameter model.",img:"https://the-decoder.com/wp-content/uploads/2026/07/thinking_machines_inkling_logo.png"},
 {src:"decoder",d:"2026-07-16",t:"Gemma 4 gets a stealth update that fixes tool calling bugs and truncated responses under the same name",u:"https://the-decoder.com/gemma-4-gets-a-stealth-update-that-fixes-tool-calling-bugs-and-truncated-responses-under-the-same-name/",s:"Google updated Gemma 4 with performance improvements without changing the version designation.",img:"https://the-decoder.com/wp-content/uploads/2026/07/Google-Gemma-4-31B-net-improvements-scaled-1.jpeg"},
 // OpenAI News
 {src:"openai",d:"2026-07-16",t:"Why teens deserve access to safe AI",u:"https://openai.com/index/why-teens-deserve-access-safe-ai/",s:"On the importance of providing teenagers with access to safe artificial intelligence systems.",img:"https://images.ctfassets.net/kftzwdyauwt9/qMYBYjbkSSEYQbsQyyfRQ/d9fe2585ed8bbf73ffee5d6ed8bcc39e/why-teens-card.jpg?w=3840&q=90&fm=webp"},
 {src:"openai",d:"2026-07-15",t:"GPT-Red: Unlocking Self-Improvement for Robustness",u:"https://openai.com/index/unlocking-self-improvement-gpt-red/",s:"GPT-Red technology designed to enable self-improvement capabilities for increased robustness.",img:"https://images.ctfassets.net/kftzwdyauwt9/6q32m87ClqE8Ovn6vD424h/05ced72e47bbe42711fbac6a082cbff2/Art_Card.png?w=3840&q=90&fm=webp"},
 {src:"openai",d:"2026-07-14",t:"How to manage AI investments in the agentic era",u:"https://openai.com/index/managing-ai-investments-in-agentic-era/",s:"Strategies for managing AI investments during the emergence of agentic systems.",img:"https://images.ctfassets.net/kftzwdyauwt9/1qXMreHMXalbFSVXr2CJXW/acbd7f4e05bd38b80a99523967ef69b7/Frame.png?w=3840&q=90&fm=webp"},
 {src:"openai",d:"2026-07-09",t:"GPT-5.6 is now the preferred model in Microsoft 365 Copilot",u:"https://openai.com/index/gpt-5-6-preferred-model-microsoft-365-copilot/",s:"GPT-5.6 selected as the default model for Microsoft 365 Copilot integration.",img:"https://images.ctfassets.net/kftzwdyauwt9/3MPipvFMxS8m3kTyCtwFgj/015747dcd34cb667a221688cfca64e0f/Frame.png?w=3840&q=90&fm=webp"},
 {src:"openai",d:"2026-07-09",t:"GPT-5.6: Frontier intelligence that scales with your ambition",u:"https://openai.com/index/gpt-5-6/",s:"Introduction of GPT-5.6 as an advanced AI model offering scalable intelligence.",img:"https://images.ctfassets.net/kftzwdyauwt9/1a9IPPV5nXWydTBosgmgYI/8e03f28ac04f26edc8bc81cdba387df1/5-6.jpg?w=3840&q=90&fm=webp"},
 {src:"openai",d:"2026-07-09",t:"OpenAI Bio Bug Bounty",u:"https://openai.com/index/bio-bug-bounty/",s:"Bug bounty program focused on identifying vulnerabilities related to biological research capabilities.",img:"https://images.ctfassets.net/kftzwdyauwt9/2wba91t9mgdv1oBPai3LTb/e48f5d6b5e44bdaafb0eac51f96458d1/bug_bounty_1_1.png?w=3840&q=90&fm=webp"},
 // Simon Willison
 {src:"simonw",d:"2026-07-15",t:"How I tricked Claude into leaking your deepest, darkest secrets",u:"https://simonwillison.net/2026/Jul/15/claude-web-fetch-exfiltration/",s:"A vulnerability in Claude's web_fetch tool allowing data exfiltration through nested links.",img:null},
 {src:"simonw",d:"2026-07-14",t:"lobste.rs is now running on SQLite",u:"https://simonwillison.net/2026/Jul/14/lobsters-sqlite/",s:"Lobsters migrated from MariaDB to SQLite, reducing costs and improving performance.",img:null},
 {src:"simonw",d:"2026-07-13",t:"DOOMQL",u:"https://simonwillison.net/2026/Jul/13/doomql/",s:"A Doom-like game built entirely in SQLite using recursive CTEs for ray tracing and game logic.",img:null},
 {src:"simonw",d:"2026-07-09",t:"The new GPT-5.6 family: Luna, Terra, Sol",u:"https://simonwillison.net/2026/Jul/9/gpt-5-6/",s:"OpenAI released three new flagship models in varying sizes with improved tool use and pricing.",img:null},
 {src:"simonw",d:"2026-07-08",t:"Rewriting Bun in Rust",u:"https://simonwillison.net/2026/Jul/8/rewriting-bun-in-rust/",s:"JavaScript runtime Bun completed a million-line rewrite from Zig to Rust using AI-assisted engineering.",img:null},
 {src:"simonw",d:"2026-07-07",t:"sqlite-utils 4.0, now with database schema migrations",u:"https://simonwillison.net/2026/Jul/7/sqlite-utils-4/",s:"Major release adding database migrations, nested transactions, and compound foreign key support.",img:null},
 // Hugging Face
 {src:"hf",d:null,t:"Introducing North Mini Code: Cohere's First Model For Developers",u:"https://huggingface.co/blog/CohereLabs/introducing-north-mini-code",s:"CohereLabs announces North Mini Code, their inaugural model designed for developer use.",img:null},
 {src:"hf",d:null,t:"Can Voice Agents Handle Bilingual Customers? Benchmarking Frontier ASR on Code-Switched Speech",u:"https://huggingface.co/blog/ServiceNow-AI/code-switching",s:"Evaluating voice agent performance with bilingual and code-switched speech inputs.",img:null},
 {src:"hf",d:null,t:"MTEB Leaderboard: From a slow demo to feature-rich leaderboard",u:"https://huggingface.co/blog/Samoed/mteb-v3-leaderboard",s:"The evolution of the MTEB Leaderboard from initial demo to comprehensive platform.",img:null},
 {src:"hf",d:null,t:"Eyes, ears, and a voice: building Reachy Mini's media stack",u:"https://huggingface.co/blog/pollen-robotics/reachy-mini-media-stack",s:"The technical architecture behind Reachy Mini's multimedia capabilities.",img:null},
 {src:"hf",d:null,t:"How to Fine-Tune Nemotron 3.5 ASR for Your Language, Domain, or Accent",u:"https://huggingface.co/blog/nvidia/fine-tuning-nemotron-35-asr",s:"NVIDIA guidance on customizing Nemotron 3.5 ASR for specific linguistic and acoustic needs.",img:null},
 // Zapier
 {src:"zapier",d:null,t:"Zapier MCP: Perform tens of thousands of actions in your AI tool",u:"https://zapier.com/blog/zapier-mcp-guide/",s:"Using Zapier MCP to let AI tools interact with thousands of apps without complex API integrations.",img:null},
 {src:"zapier",d:"2026-05-29",t:"What is AI agent orchestration?",u:"https://zapier.com/blog/ai-agent-orchestration/",s:"Coordinating multiple AI agents to work together for complex automation tasks.",img:null},
 {src:"zapier",d:"2026-05-29",t:"How to build multi-agent systems with MCP",u:"https://zapier.com/blog/multi-agent-systems-mcp/",s:"Tutorial on creating multi-agent systems using Zapier's MCP technology for advanced automation.",img:null},
 {src:"zapier",d:null,t:"Zapier vs. Workato for enterprise agents: Which is best? [2026]",u:"https://zapier.com/blog/zapier-vs-workato-for-enterprise-agents/",s:"Comparison of Zapier and Workato platforms for implementing enterprise-level AI agents.",img:"https://images.ctfassets.net/lzny33ho1g45/7lv7XsZiy5E7eaTqXOSo3x/6ea19be7727e419419ce4946206f1cf0/zapier-vs-workato-hero.jpg"},
 {src:"zapier",d:"2026-05-29",t:"What are webhooks?",u:"https://zapier.com/blog/what-are-webhooks/",s:"How webhooks enable real-time data transmission between applications.",img:"https://images.ctfassets.net/lzny33ho1g45/what-are-webhooks-p-img/107d536d4faf5fa18ab81885e6ce438e/Hero.jpg"},
 // ScienceDaily Nutrition
 {src:"sd-nut",d:"2026-05-23",t:"Scientists Warn Popular Vitamin D Supplement May Have a \"Previously Unknown\" Downside",u:"https://www.sciencedaily.com/releases/2026/05/260523021820.htm",s:"Vitamin D2 supplements may reduce body levels of the more effective D3 form.",img:null},
 {src:"sd-nut",d:"2026-05-22",t:"Scientists Uncover Cancer-causing Chemicals Hidden in Everyday Foods",u:"https://www.sciencedaily.com/releases/2026/05/260522030853.htm",s:"PAH compounds form in foods exposed to high-heat cooking methods like grilling and frying.",img:null},
 {src:"sd-nut",d:"2026-05-22",t:"Surprising Study Finds Beef Doesn't Worsen Blood Sugar or Diabetes Risk",u:"https://www.sciencedaily.com/releases/2026/05/260521072416.htm",s:"Daily beef consumption showed no negative effects on blood sugar control in prediabetic adults.",img:null},
 {src:"sd-nut",d:"2026-05-22",t:"Scientists Warn That Current Vitamin B12 Guidelines May Be Putting Your Brain at Risk",u:"https://www.sciencedaily.com/releases/2026/05/260522031001.htm",s:"Current B12 recommendations may be insufficient to protect aging brains from cognitive decline.",img:null},
 {src:"sd-nut",d:"2026-05-21",t:"Childhood Junk Food May Rewire the Brain for Life",u:"https://www.sciencedaily.com/releases/2026/05/260520093807.htm",s:"Early consumption of high-fat, high-sugar diets produces lasting changes to appetite regulation.",img:null},
 {src:"sd-nut",d:"2026-05-21",t:"Scientists Discover the Nutrient That Can Supercharge Cellular Energy",u:"https://www.sciencedaily.com/releases/2026/05/260520233221.htm",s:"Leucine from protein-rich foods protects mitochondrial energy-production proteins in cells.",img:null},
 // Fit Foodie Finds
 {src:"fff",d:null,t:"10 No-Cook Dinners (for when it's too hot to function!)",u:"https://fitfoodiefinds.com/10-no-cook-dinners/",s:"No-cook dinner recipes ideal for hot weather when cooking feels overwhelming.",img:"https://fitfoodiefinds.com/wp-content/uploads/2024/02/Spring-Roll-Salad-1-600x896.jpg"},
 {src:"fff",d:null,t:"Peanut Butter Protein Balls (No Food Processor!)",u:"https://fitfoodiefinds.com/peanut-butter-protein-balls-recipe/",s:"Easy protein-packed snack made without requiring a food processor.",img:"https://fitfoodiefinds.com/wp-content/uploads/2020/04/protein-balls-f2-600x896.jpg"},
 {src:"fff",d:null,t:"30 Best Cottage Cheese Recipes (High Protein!)",u:"https://fitfoodiefinds.com/high-protein-cottage-cheese-recipes/",s:"A collection of 30 high-protein recipes featuring cottage cheese.",img:"https://fitfoodiefinds.com/wp-content/uploads/2024/09/COTTAGE-CHEESE-RECIPES-600x896.png"},
 {src:"fff",d:null,t:"Cottage Cheese Pizza Crust (No-Rise & Protein-Packed!)",u:"https://fitfoodiefinds.com/no-rise-pizza-dough/",s:"No-rise pizza dough made with cottage cheese for added protein.",img:"https://fitfoodiefinds.com/wp-content/uploads/2025/02/No-Rise-Pizza-Dough-02-600x896.jpg"},
 {src:"fff",d:null,t:"Strawberry Smoothie (4 Ingredients, No Ice!)",u:"https://fitfoodiefinds.com/strawberry-smoothie/",s:"Simple strawberry smoothie requiring only four ingredients and no ice.",img:"https://fitfoodiefinds.com/wp-content/uploads/2019/03/STRAWBERRY-f2-600x896.png"},
 // Wellness Mama
 {src:"wm",d:"2026-07-14",t:"Healthy Sesame Ginger Cabbage Rolls",u:"https://wellnessmama.com/recipes/cabbage-rolls/",s:"A healthier take on Chinese food featuring cabbage rolls with sesame and ginger flavors.",img:"https://wellnessmama.com/wp-content/uploads/asian-cabbage-rolls.jpg"},
 {src:"wm",d:"2026-07-09",t:"DIY Natural Tinted Lip Sunscreen",u:"https://wellnessmama.com/beauty/lip-sunscreen/",s:"A homemade tinted lip balm with sun protection using natural ingredients.",img:"https://wellnessmama.com/wp-content/uploads/tinted-lip-sunscreen.png"},
 {src:"wm",d:"2026-07-07",t:"Broccoli Cheddar Egg Bake (Easy High-Protein)",u:"https://wellnessmama.com/recipes/egg-bake/",s:"A make-ahead breakfast recipe emphasizing protein with broccoli and cheddar.",img:"https://wellnessmama.com/wp-content/uploads/egg-bake.jpg"},
 {src:"wm",d:"2026-07-02",t:"Sunlight, Red Light, and How to Harness Light's Benefits for Health",u:"https://wellnessmama.com/health/light-benefits/",s:"How different light wavelengths impact wellness and health outcomes.",img:"https://wellnessmama.com/wp-content/uploads/light-benefits.png"},
 {src:"wm",d:"2026-06-26",t:"The Ultimate List of Minerals Benefits and How to Use Them",u:"https://wellnessmama.com/health/mineral-benefits/",s:"A comprehensive guide to mineral supplementation and its health applications.",img:"https://wellnessmama.com/wp-content/uploads/mineral-benefits.png"},
 // mindbodygreen
 {src:"mbg",d:"2026-07-16",t:"Start Your Day With Coffee? Here's How To Make Yours Even Healthier",u:"https://www.mindbodygreen.com/articles/start-your-day-with-coffee-5-waysto-make-yours-even-healthier",s:"Strategies to enhance the nutritional benefits of your morning coffee.",img:"https://mindbodygreen-res.cloudinary.com/image/upload/c_crop,x_0,y_25,w_1500,h_843/c_fill,g_center,w_400,h_224,q_90,f_auto,fl_lossy/org/ma0i48mwzjx4sbyk4.jpg"},
 {src:"mbg",d:null,t:"This Supplement Helps Rebuild Muscle From The Inside Out, New Study Shows",u:"https://www.mindbodygreen.com/articles/collagen-helps-rebuild-muscles-from-the-inside-out-new-study",s:"Research demonstrating collagen's role in muscle tissue recovery.",img:null},
 {src:"mbg",d:null,t:"This Breathing Trick Doesn't Just Lower Stress — It Changes Your Brain",u:"https://www.mindbodygreen.com/articles/how-longer-exhale-could-change-way-you-think",s:"How extended exhalation techniques influence neurological function beyond stress relief.",img:null},
 {src:"mbg",d:null,t:"This Might Be The Most Underrated Vitamin For Healthy Bones",u:"https://www.mindbodygreen.com/articles/this-vitamin-may-be-just-as-important-for-your-bones-as-calcium",s:"An overlooked nutrient critical for bone health alongside calcium.",img:null},
 {src:"mbg",d:null,t:"2 New Biomarkers Could Detect Lyme Disease Days Earlier Than Standard Tests",u:"https://www.mindbodygreen.com/articles/2-new-blood-proteins-may-detect-lyme-disease-earlier",s:"Emerging blood markers that enable faster Lyme disease diagnosis.",img:null},
 // Dr. Axe
 {src:"draxe",d:"2026-07-14",t:"30 Best Essential Oils for Summer Wellness: Uses, Safety and Summer Blends",u:"https://draxe.com/essential-oils/essential-oils-for-summer/",s:"Essential oils can offer refreshing and uplifting experiences during the summer season.",img:"https://draxe.com/wp-content/uploads/2023/07/Shutterstock_600904898-1.jpg"},
 {src:"draxe",d:"2026-07-13",t:"Grapes Nutrition: Benefits, Calories and Are Grapes Good for You?",u:"https://draxe.com/nutrition/grapes-nutrition/",s:"Grapes are versatile fruits used to make wine, raisins, and grapeseed products.",img:"https://draxe.com/wp-content/uploads/2020/09/DrAxeGrapeNutritionThumbnail.jpg"},
 {src:"draxe",d:"2026-07-12",t:"20 Cold Soup Recipes for Summer (& Beyond)",u:"https://draxe.com/nutrition/cold-soup/",s:"Cold soups provide lighter alternatives to traditional warm soup dishes during warmer months.",img:"https://draxe.com/wp-content/uploads/2016/06/DrAxeColdSoupsThumbnail.jpg"},
 {src:"draxe",d:"2026-07-11",t:"22+ Best Cooling Foods and Cooling Herbs to Help Beat the Heat",u:"https://draxe.com/nutrition/cooling-foods-herbs/",s:"Cooling foods and herbs help balance excess internal heat during hot weather.",img:"https://draxe.com/wp-content/uploads/2021/08/CoolingFoodsThumbnail.jpg"},
 {src:"draxe",d:"2026-07-10",t:"Nutrient Absorption: Why It Matters and How to Improve It Naturally",u:"https://draxe.com/nutrition/nutrient-absorption/",s:"Proper nutrient absorption requires more than eating nutritious foods; it demands optimal digestive function.",img:"https://draxe.com/wp-content/uploads/2026/07/shutterstock_2497350597.jpg"},
 {src:"draxe",d:"2026-07-09",t:"Strength Training for Longevity: Study Finds Resistance Exercise May Help Support a Longer Life",u:"https://draxe.com/fitness/strength-training-for-longevity/",s:"Research indicates that resistance exercise may contribute to increased longevity.",img:"https://draxe.com/wp-content/uploads/2026/07/shutterstock_2741487225.jpg"},
 // Janet Lansbury (dates approximated from URLs, month precision)
 {src:"lansbury",d:"2026-03-01",t:"Why Parents Need RIE (with Melani Ladygo)",u:"https://www.janetlansbury.com/2026/03/why-parents-need-rie-with-melani-ladygo/",s:"Podcast discussion exploring the importance of RIE principles for parents in raising children.",img:null},
 {src:"lansbury",d:"2025-10-01",t:"Making a Successful Transition to Preschool (with Mr. Chazz)",u:"https://www.janetlansbury.com/2025/10/making-a-successful-transition-to-preschool-with-mr-chazz/",s:"Guidance on helping children successfully transition into preschool settings.",img:null},
 {src:"lansbury",d:"2025-10-01",t:"The Bad Advice I Gave About Toilet Training",u:"https://www.janetlansbury.com/2025/10/the-bad-advice-i-gave-about-toilet-training/",s:"Janet reflects on previous toilet training recommendations and provides corrected guidance.",img:null},
 {src:"lansbury",d:"2025-08-01",t:"Rejection, Exclusion, Teasing — What to do When Friends Aren't Kind",u:"https://www.janetlansbury.com/2025/08/rejection-exclusion-teasing-what-to-do-when-friends-arent-kind/",s:"Parental strategies for addressing peer rejection and unkind friend dynamics.",img:null},
 // Hey Sigmund
 {src:"sigmund",d:null,t:"My Child Has Anxiety: Why avoidance makes it worse, and what to do instead",u:"https://heysigmund.com/my-child-has-anxiety-why-avoidance-makes-it-worse-and-what-to-do-intead/",s:"How avoidance reinforces anxiety in children, with strategies for parents to help kids build courage.",img:null},
 {src:"sigmund",d:null,t:"The Power of 'and' to Build Their Brave",u:"https://heysigmund.com/the-power-of-and-to-build-their-brave/",s:"How using the word 'and' instead of 'but' can help parents support anxious children more effectively.",img:null},
 {src:"sigmund",d:null,t:"Unplugged (Sort Of): Helping Children Cope with Screen and Social Media Limits in a Digital World",u:"https://heysigmund.com/unplugged-sort-of-helping-children-cope-with-screen-and-social-media-limits-in-a-digital-world/",s:"Strategies for helping kids manage restrictions on screen time and social media.",img:null},
 {src:"sigmund",d:null,t:"The Key to Crime Prevention and Mental Illness Prevention — Why it Lies in Our Schools and Early Childhood Centres",u:"https://heysigmund.com/schools-early-childhood-centres/",s:"The role of educational institutions in promoting mental health from early stages.",img:null},
 // Motherly
 {src:"motherly",d:"2026-06-29",t:"The motherhood penalty is costing women more than just playing time",u:"https://www.mother.ly/health-wellness/womens-health/motherhood-penalty-in-sports/",s:"How motherhood affects women's participation and opportunities in sports.",img:"https://ens3xeax5jd.exactdn.com/wp-content/uploads/2026/06/motherhood-penalty-in-sports.jpg"},
 {src:"motherly",d:"2026-06-25",t:"The personal safety skill every woman already has — and needs to pass on to her daughter",u:"https://www.mother.ly/health-wellness/womens-health/personal-safety-for-women-and-girls/",s:"An essential personal safety skill women can teach their daughters.",img:"https://kinsta-wp-media.s3.amazonaws.com/wp-content/uploads/2026/06/26110827/personal-safety-for-women-1440x810.jpg"},
 {src:"motherly",d:"2026-06-24",t:"The dermatologist who wants to liberate you from your 12-step routine (especially during pregnancy)",u:"https://www.mother.ly/pregnancy/pregnancy-products/clean-beauty-myths-dermatologist-postpartum-skincare/",s:"A dermatologist challenges common skincare misconceptions and discusses simplified routines.",img:"https://kinsta-wp-media.s3.amazonaws.com/wp-content/uploads/2026/06/26110829/clean-beauty-myths.jpg"},
 {src:"motherly",d:"2026-06-22",t:"What does emotional maturity in children actually look like? A psychologist explains, age by age",u:"https://www.mother.ly/child/child-learn-play/emotional-maturity-in-children/",s:"Psychotherapist Dr. Lindsay Gibson explains how emotional maturity develops at different ages.",img:"https://kinsta-wp-media.s3.amazonaws.com/wp-content/uploads/2026/06/26110830/emotional-maturity-1440x810.jpg"},
 {src:"motherly",d:null,t:"Recess isn't a reward. It's a requirement. Here's what the new AAP recess guidelines mean for your kid.",u:"https://www.mother.ly/child/child-learn-play/aap-recess-guidelines/",s:"New AAP guidelines reframe recess as essential rather than optional for children.",img:"https://ens3xeax5jd.exactdn.com/wp-content/uploads/2026/05/aap-recess-guidelines.jpg"},
 {src:"motherly",d:null,t:"PCOS has a new name. It's about time.",u:"https://www.mother.ly/health-wellness/womens-health/pcos-new-name-pmos/",s:"The condition formerly known as PCOS receives a name change reflecting current medical understanding.",img:"https://ens3xeax5jd.exactdn.com/wp-content/uploads/2026/05/pcos-1440x810.jpg"},
 // Simple Homeschool
 {src:"simpleh",d:null,t:"4 Fun Ways to Enjoy Summer Homeschooling",u:"https://simplehomeschool.net/summer-homeschooling/",s:"Engaging activities to make summer homeschooling enjoyable for families.",img:null},
 {src:"simpleh",d:null,t:"How to homeschool a kid who hates to write",u:"https://simplehomeschool.net/hates-to-write/",s:"Practical strategies for helping reluctant writers develop confidence.",img:null},
 {src:"simpleh",d:null,t:"Homeschooling with Trauma: My Story",u:"https://simplehomeschool.net/homeschooling-with-trauma/",s:"A personal account of navigating homeschooling while managing trauma.",img:null},
];

function loadSnapshot(){
  const items = SNAPSHOT.map((r,i)=>{
    const src = SOURCES.find(s=>s.id===r.src); if(!src || !r.u || !r.t) return null;
    const ts = r.d ? (Date.parse(r.d) || SNAPSHOT_TS) : SNAPSHOT_TS;
    return {
      id: hash(normalizeLink(r.u)), link: r.u, title: r.t, ts,
      src: src.id, cat: src.cat, img: r.img||null, snippet: r.s||'', author:'',
      content:'', snap:true,
      brief: (typeof BRIEFS!=='undefined' && BRIEFS[i]) || null,   // Claude-written AI brief
    };
  }).filter(Boolean);
  mergeArticles(items);
  return items.length;
}
